theme: jekyll-theme-slate
title: Welcome to TK's Terrific Project Repository! (Test Version)
description: This site will house every update to my Senior Project, from Analysis Reports, to Weekly Time Logs, to Progress Reports. Check in weekly to see all the updates! (Test Version)
